services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "13306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "xiaozhi", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  node:
    image: ghcr.io/augusdin/xiaozhi-esp32-server-java-node:main
    build:
      context: .
      dockerfile: Dockerfile-node
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8084:8084"
    networks:
      - app-network
    environment:
      - API_URL=http://server:8091

  server:
    image: ghcr.io/augusdin/xiaozhi-esp32-server-java-server:main
    build:
      context: .
      dockerfile: Dockerfile-server
      # 移除Vosk模型相关配置
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8091:8091"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/xiaozhi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=xiaozhi
      - SPRING_DATASOURCE_PASSWORD=123456
      # 配置FunASR服务地址，默认指向宿主机的独立 FunASR 服务
      - FUNASR_API_URL=ws://host.docker.internal:10095/
      # 邮箱配置
      - EMAIL_SMTP_USERNAME=noreply@xiaozhi.com
      - EMAIL_SMTP_PASSWORD=defaultpassword
    # 优化内存限制适配2GB RAM环境
    deploy:
      resources:
        limits:
          memory: 450M
        reservations:
          memory: 150M
    restart: unless-stopped
    # 增加健康检查启动时间，因为无需加载模型启动更快
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
